// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_INICIO
void ui_INICIO_screen_init(void);
void ui_event_INICIO(lv_event_t * e);
lv_obj_t * ui_INICIO;
lv_obj_t * ui_Image1;
// CUSTOM VARIABLES


// SCREEN: ui_HOME
void ui_HOME_screen_init(void);
lv_obj_t * ui_HOME;
lv_obj_t * ui_imgBg;
lv_obj_t * ui_Group_Gauge;
lv_obj_t * ui_imgGaugeSpeed;
lv_obj_t * ui_imgCursorSpeed;
lv_obj_t * ui_Group_Speed;
lv_obj_t * ui_Container1;
lv_obj_t * ui_lblSpeedUnit;
lv_obj_t * ui_lblSpeedNumber;
lv_obj_t * ui_Group_Ritmo;
lv_obj_t * ui_LabelVarRitm;
lv_obj_t * ui_Label_kmh4;
lv_obj_t * ui_Group_Right_Side;
lv_obj_t * ui_Group_Real_Time2;
lv_obj_t * ui_Group_Data_Inter;
lv_obj_t * ui_lblInterTittle;
lv_obj_t * ui_groupPtllEntrenaInter2;
lv_obj_t * ui_lblTittleTipoPasada2;
lv_obj_t * ui_groupPtllEntrenaInter;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Series;
lv_obj_t * ui_Pasadas;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Container2;
lv_obj_t * ui_lblNumSeries;
lv_obj_t * ui_Container3;
lv_obj_t * ui_lblNumPasadas;
lv_obj_t * ui_Group_Distance;
lv_obj_t * ui_lblDistanceTittle;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_lblDistanceNumber;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_lblDistanceUnit;
lv_obj_t * ui_Group_Time;
lv_obj_t * ui_lblTimeTittle;
lv_obj_t * ui_lblTimeNumber;
lv_obj_t * ui_Group_Header_Up;
lv_obj_t * ui_imgBgGroupSettingsUp;
lv_obj_t * ui_imgWifi;
lv_obj_t * ui_lblNetName;
lv_obj_t * ui_lblDate;
lv_obj_t * ui_lblTime;
void ui_event_btnConfig(lv_event_t * e);
lv_obj_t * ui_btnConfig;
lv_obj_t * ui_Group_Settings_Down;
lv_obj_t * ui_imgBgGroupSettingsDown;
lv_obj_t * ui_Button_Group;
void ui_event_btnRealTime(lv_event_t * e);
lv_obj_t * ui_btnRealTime;
void ui_event_btnInter(lv_event_t * e);
lv_obj_t * ui_btnInter;
lv_obj_t * ui_groupReinitbtn;
void ui_event_btnReinicio(lv_event_t * e);
lv_obj_t * ui_btnReinicio;
lv_obj_t * ui_lblReiniciobtn;
lv_obj_t * ui_groupPausa;
lv_obj_t * ui_lblTittlePausa;
lv_obj_t * ui_lblPausa;
lv_obj_t * ui_Container5;
// CUSTOM VARIABLES


// SCREEN: ui_CONFIG
void ui_CONFIG_screen_init(void);
void ui_event_CONFIG(lv_event_t * e);
lv_obj_t * ui_CONFIG;
lv_obj_t * ui_Dropdown1;
void ui_event_btnConfig2(lv_event_t * e);
lv_obj_t * ui_btnConfig2;
lv_obj_t * ui_lblNetTittle;
void ui_event_passArea(lv_event_t * e);
lv_obj_t * ui_passArea;
lv_obj_t * ui_imgWifi2;
lv_obj_t * ui_llblPswTittle;
lv_obj_t * ui_lblNetworkIP;
lv_obj_t * ui_lblFirmwareVersion;
lv_obj_t * ui_lblNumMaquina;
lv_obj_t * ui_lblOdoMaquina;
void ui_event_btnConectWifi(lv_event_t * e);
lv_obj_t * ui_btnConectWifi;
void ui_event_btnDisconectWifi1(lv_event_t * e);
lv_obj_t * ui_btnDisconectWifi1;
lv_obj_t * ui_lblbtnConectar;
lv_obj_t * ui_lblbtnDesconectar;
lv_obj_t * ui_lblInfo;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES


// SCREEN: ui_PROGRAMADO
void ui_PROGRAMADO_screen_init(void);
lv_obj_t * ui_PROGRAMADO;
lv_obj_t * ui_groupSeries;
lv_obj_t * ui_lblTittleSeries;
lv_obj_t * ui_rollerNumSeries;
lv_obj_t * ui_lblTittlePausaSeries;
lv_obj_t * ui_lblUnitPauseSeries;
lv_obj_t * ui_rollerMacropausa;
lv_obj_t * ui_lblTittleSeries2;
void ui_event_btnRightToPasadas(lv_event_t * e);
lv_obj_t * ui_btnRightToPasadas;
void ui_event_btnLeftToTipoPasadas(lv_event_t * e);
lv_obj_t * ui_btnLeftToTipoPasadas;
lv_obj_t * ui_lblTittleSeries1;
lv_obj_t * ui_lblTittleSeries3;
lv_obj_t * ui_Group_Buttons;
lv_obj_t * ui_GroupOk;
void ui_event_btnOk(lv_event_t * e);
lv_obj_t * ui_btnOk;
lv_obj_t * ui_imgOk;
// CUSTOM VARIABLES


// SCREEN: ui_PROGRAMADO_2
void ui_PROGRAMADO_2_screen_init(void);
lv_obj_t * ui_PROGRAMADO_2;
lv_obj_t * ui_groupPasadas;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_rollerMicropausaSeg;
lv_obj_t * ui_Label3;
lv_obj_t * ui_rollerMicropausaMin;
lv_obj_t * ui_rollerNumPasadas;
void ui_event_btnRightToTipoPasadas(lv_event_t * e);
lv_obj_t * ui_btnRightToTipoPasadas;
void ui_event_btnLeftToSeries(lv_event_t * e);
lv_obj_t * ui_btnLeftToSeries;
lv_obj_t * ui_lblTittleSeries5;
lv_obj_t * ui_lblTittleSeries6;
lv_obj_t * ui_Group_Buttons2;
lv_obj_t * ui_GroupOk2;
void ui_event_btnOk2(lv_event_t * e);
lv_obj_t * ui_btnOk2;
lv_obj_t * ui_imgOk2;
// CUSTOM VARIABLES


// SCREEN: ui_PROGRAMADO_3
void ui_PROGRAMADO_3_screen_init(void);
lv_obj_t * ui_PROGRAMADO_3;
lv_obj_t * ui_groupTipoPasadas;
lv_obj_t * ui_groupTipoPasadaTiempo;
lv_obj_t * ui_lblUnitTittlePasadaSeg;
lv_obj_t * ui_rollerPasadaTiempoSeg;
lv_obj_t * ui_lblUnitTittlePasadaMin;
lv_obj_t * ui_rollerPasadaTiempoMin;
lv_obj_t * ui_groupTipoPasadaDistancia;
lv_obj_t * ui_Label5;
lv_obj_t * ui_rollerPasadaDistancia;
lv_obj_t * ui_lblTittleTipoPasadaPor;
lv_obj_t * ui_lblTittleTipoPasada;
void ui_event_swTipoPasada(lv_event_t * e);
lv_obj_t * ui_swTipoPasada;
void ui_event_btnRightSeries(lv_event_t * e);
lv_obj_t * ui_btnRightSeries;
void ui_event_btnLeftToPasadas(lv_event_t * e);
lv_obj_t * ui_btnLeftToPasadas;
lv_obj_t * ui_lblTittleSeries7;
lv_obj_t * ui_lblTittleSeries8;
lv_obj_t * ui_Group_Buttons3;
lv_obj_t * ui_GroupOk3;
void ui_event_btnOk3(lv_event_t * e);
lv_obj_t * ui_btnOk3;
lv_obj_t * ui_imgOk3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_bg[1] = {&ui_img_bg1_png};
const lv_img_dsc_t * ui_imgset_icn_x[1] = {&ui_img_icn_x2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_INICIO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_ON, 250, 5000, &ui_HOME_screen_init);
    }
}

void ui_event_btnConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CONFIG, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_CONFIG_screen_init);
    }
}

void ui_event_btnRealTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnInter, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_btnRealTime, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_btnRealTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_lblInterTittle, target, "ENTRENA LIBRE", "");
    }
    if(event_code == LV_EVENT_CLICKED) {
        btnLibreOn(e);
    }
}

void ui_event_btnInter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_btnInter, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_btnRealTime, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_btnRealTime, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_lblInterTittle, target, "PROGRAMADO", "");
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_PROGRAMADO, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_screen_init);
        btnProgramaOn(e);
    }
}

void ui_event_btnReinicio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        reinit_ent(e);
    }
}

void ui_event_CONFIG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        config_loaded(e);
    }
}

void ui_event_btnConfig2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HOME_screen_init);
        change_to_home(e);
    }
}

void ui_event_passArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_btnConectWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        conect_wifi(e);
    }
}

void ui_event_btnDisconectWifi1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        disconect_wifi(e);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_btnRightToPasadas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMADO_2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_2_screen_init);
    }
}

void ui_event_btnLeftToTipoPasadas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMADO_3, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_3_screen_init);
    }
}

void ui_event_btnOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnProgramOk(e);
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HOME_screen_init);
    }
}

void ui_event_btnRightToTipoPasadas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMADO_3, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_3_screen_init);
    }
}

void ui_event_btnLeftToSeries(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMADO, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_screen_init);
    }
}

void ui_event_btnOk2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnProgramOk(e);
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HOME_screen_init);
    }
}

void ui_event_swTipoPasada(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_groupTipoPasadaDistancia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_groupTipoPasadaTiempo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_checked_set_text_value(ui_lblTittleTipoPasada, target, "DISTANCIA", "TIEMPO");
        _ui_checked_set_text_value(ui_lblTittleTipoPasada2, target, "por DISTANCIA", "por TIEMPO");
    }
}

void ui_event_btnRightSeries(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMADO, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_screen_init);
    }
}

void ui_event_btnLeftToPasadas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PROGRAMADO_2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_PROGRAMADO_2_screen_init);
    }
}

void ui_event_btnOk3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        btnProgramOk(e);
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_HOME_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_INICIO_screen_init();
    ui_HOME_screen_init();
    ui_CONFIG_screen_init();
    ui_PROGRAMADO_screen_init();
    ui_PROGRAMADO_2_screen_init();
    ui_PROGRAMADO_3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_INICIO);
}
