// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#ifndef _WILLI_NEW7_UI_H
#define _WILLI_NEW7_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_INICIO
void ui_INICIO_screen_init(void);
void ui_event_INICIO(lv_event_t * e);
extern lv_obj_t * ui_INICIO;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_HOME
void ui_HOME_screen_init(void);
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_imgBg;
extern lv_obj_t * ui_Group_Gauge;
extern lv_obj_t * ui_imgGaugeSpeed;
extern lv_obj_t * ui_imgCursorSpeed;
extern lv_obj_t * ui_Group_Speed;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_lblSpeedUnit;
extern lv_obj_t * ui_lblSpeedNumber;
extern lv_obj_t * ui_Group_Ritmo;
extern lv_obj_t * ui_LabelVarRitm;
extern lv_obj_t * ui_Label_kmh4;
extern lv_obj_t * ui_Group_Right_Side;
extern lv_obj_t * ui_Group_Real_Time2;
extern lv_obj_t * ui_Group_Data_Inter;
extern lv_obj_t * ui_lblInterTittle;
extern lv_obj_t * ui_groupPtllEntrenaInter2;
extern lv_obj_t * ui_lblTittleTipoPasada2;
extern lv_obj_t * ui_groupPtllEntrenaInter;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Series;
extern lv_obj_t * ui_Pasadas;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_lblNumSeries;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_lblNumPasadas;
extern lv_obj_t * ui_Group_Distance;
extern lv_obj_t * ui_lblDistanceTittle;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_lblDistanceNumber;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblDistanceUnit;
extern lv_obj_t * ui_Group_Time;
extern lv_obj_t * ui_lblTimeTittle;
extern lv_obj_t * ui_lblTimeNumber;
extern lv_obj_t * ui_Group_Header_Up;
extern lv_obj_t * ui_imgBgGroupSettingsUp;
extern lv_obj_t * ui_imgWifi;
extern lv_obj_t * ui_lblNetName;
extern lv_obj_t * ui_lblDate;
extern lv_obj_t * ui_lblTime;
void ui_event_btnConfig(lv_event_t * e);
extern lv_obj_t * ui_btnConfig;
extern lv_obj_t * ui_Group_Settings_Down;
extern lv_obj_t * ui_imgBgGroupSettingsDown;
extern lv_obj_t * ui_Button_Group;
void ui_event_btnRealTime(lv_event_t * e);
extern lv_obj_t * ui_btnRealTime;
void ui_event_btnInter(lv_event_t * e);
extern lv_obj_t * ui_btnInter;
extern lv_obj_t * ui_groupReinitbtn;
void ui_event_btnReinicio(lv_event_t * e);
extern lv_obj_t * ui_btnReinicio;
extern lv_obj_t * ui_lblReiniciobtn;
extern lv_obj_t * ui_groupPausa;
extern lv_obj_t * ui_lblTittlePausa;
extern lv_obj_t * ui_lblPausa;
extern lv_obj_t * ui_Container5;
// CUSTOM VARIABLES

// SCREEN: ui_CONFIG
void ui_CONFIG_screen_init(void);
void ui_event_CONFIG(lv_event_t * e);
extern lv_obj_t * ui_CONFIG;
extern lv_obj_t * ui_Dropdown1;
void ui_event_btnConfig2(lv_event_t * e);
extern lv_obj_t * ui_btnConfig2;
extern lv_obj_t * ui_lblNetTittle;
void ui_event_passArea(lv_event_t * e);
extern lv_obj_t * ui_passArea;
extern lv_obj_t * ui_imgWifi2;
extern lv_obj_t * ui_llblPswTittle;
extern lv_obj_t * ui_lblNetworkIP;
extern lv_obj_t * ui_lblFirmwareVersion;
extern lv_obj_t * ui_lblNumMaquina;
extern lv_obj_t * ui_lblOdoMaquina;
void ui_event_btnConectWifi(lv_event_t * e);
extern lv_obj_t * ui_btnConectWifi;
void ui_event_btnDisconectWifi1(lv_event_t * e);
extern lv_obj_t * ui_btnDisconectWifi1;
extern lv_obj_t * ui_lblbtnConectar;
extern lv_obj_t * ui_lblbtnDesconectar;
extern lv_obj_t * ui_lblInfo;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_PROGRAMADO
void ui_PROGRAMADO_screen_init(void);
extern lv_obj_t * ui_PROGRAMADO;
extern lv_obj_t * ui_groupSeries;
extern lv_obj_t * ui_lblTittleSeries;
extern lv_obj_t * ui_rollerNumSeries;
extern lv_obj_t * ui_lblTittlePausaSeries;
extern lv_obj_t * ui_lblUnitPauseSeries;
extern lv_obj_t * ui_rollerMacropausa;
extern lv_obj_t * ui_lblTittleSeries2;
void ui_event_btnRightToPasadas(lv_event_t * e);
extern lv_obj_t * ui_btnRightToPasadas;
void ui_event_btnLeftToTipoPasadas(lv_event_t * e);
extern lv_obj_t * ui_btnLeftToTipoPasadas;
extern lv_obj_t * ui_lblTittleSeries1;
extern lv_obj_t * ui_lblTittleSeries3;
extern lv_obj_t * ui_Group_Buttons;
extern lv_obj_t * ui_GroupOk;
void ui_event_btnOk(lv_event_t * e);
extern lv_obj_t * ui_btnOk;
extern lv_obj_t * ui_imgOk;
// CUSTOM VARIABLES

// SCREEN: ui_PROGRAMADO_2
void ui_PROGRAMADO_2_screen_init(void);
extern lv_obj_t * ui_PROGRAMADO_2;
extern lv_obj_t * ui_groupPasadas;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_rollerMicropausaSeg;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_rollerMicropausaMin;
extern lv_obj_t * ui_rollerNumPasadas;
void ui_event_btnRightToTipoPasadas(lv_event_t * e);
extern lv_obj_t * ui_btnRightToTipoPasadas;
void ui_event_btnLeftToSeries(lv_event_t * e);
extern lv_obj_t * ui_btnLeftToSeries;
extern lv_obj_t * ui_lblTittleSeries5;
extern lv_obj_t * ui_lblTittleSeries6;
extern lv_obj_t * ui_Group_Buttons2;
extern lv_obj_t * ui_GroupOk2;
void ui_event_btnOk2(lv_event_t * e);
extern lv_obj_t * ui_btnOk2;
extern lv_obj_t * ui_imgOk2;
// CUSTOM VARIABLES

// SCREEN: ui_PROGRAMADO_3
void ui_PROGRAMADO_3_screen_init(void);
extern lv_obj_t * ui_PROGRAMADO_3;
extern lv_obj_t * ui_groupTipoPasadas;
extern lv_obj_t * ui_groupTipoPasadaTiempo;
extern lv_obj_t * ui_lblUnitTittlePasadaSeg;
extern lv_obj_t * ui_rollerPasadaTiempoSeg;
extern lv_obj_t * ui_lblUnitTittlePasadaMin;
extern lv_obj_t * ui_rollerPasadaTiempoMin;
extern lv_obj_t * ui_groupTipoPasadaDistancia;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_rollerPasadaDistancia;
extern lv_obj_t * ui_lblTittleTipoPasadaPor;
extern lv_obj_t * ui_lblTittleTipoPasada;
void ui_event_swTipoPasada(lv_event_t * e);
extern lv_obj_t * ui_swTipoPasada;
void ui_event_btnRightSeries(lv_event_t * e);
extern lv_obj_t * ui_btnRightSeries;
void ui_event_btnLeftToPasadas(lv_event_t * e);
extern lv_obj_t * ui_btnLeftToPasadas;
extern lv_obj_t * ui_lblTittleSeries7;
extern lv_obj_t * ui_lblTittleSeries8;
extern lv_obj_t * ui_Group_Buttons3;
extern lv_obj_t * ui_GroupOk3;
void ui_event_btnOk3(lv_event_t * e);
extern lv_obj_t * ui_btnOk3;
extern lv_obj_t * ui_imgOk3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logoj2f_png);    // assets/logoJ2F.png
LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_gauge_velocidad_png);    // assets/gauge_velocidad.png
LV_IMG_DECLARE(ui_img_speed_indicator_png);    // assets/speed_indicator.png
LV_IMG_DECLARE(ui_img_settings_up_png);    // assets/settings_up.png
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_icn_settings_png);    // assets/icn_settings.png
LV_IMG_DECLARE(ui_img_settings_down_png);    // assets/settings_down.png
LV_IMG_DECLARE(ui_img_icn_run_png);    // assets/icn_run.png
LV_IMG_DECLARE(ui_img_icn_clock_png);    // assets/icn_clock.png
LV_IMG_DECLARE(ui_img_icn_x2_png);    // assets/icn_x2.png
LV_IMG_DECLARE(ui_img_icn_arrow_png);    // assets/icn_arrow.png
LV_IMG_DECLARE(ui_img_icn_arrow_left_png);    // assets/icn_arrow_left.png
LV_IMG_DECLARE(ui_img_icn_ok_png);    // assets/icn_ok.png

// FONTS
LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Big_2);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Medium_26);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
