// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btnLibreOn(lv_event_t * e);
void btnProgramaOn(lv_event_t * e);
void reinit_ent(lv_event_t * e);
void config_loaded(lv_event_t * e);
void change_to_home(lv_event_t * e);
void conect_wifi(lv_event_t * e);
void disconect_wifi(lv_event_t * e);
void btnProgramOk(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
