// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#include "../ui.h"

void ui_CONFIG_screen_init(void)
{
    ui_CONFIG = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CONFIG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CONFIG, lv_color_hex(0x202820), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CONFIG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_CONFIG);
    lv_dropdown_set_options(ui_Dropdown1, "");
    lv_obj_set_width(ui_Dropdown1, 250);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, lv_pct(-43));
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_btnConfig2 = lv_btn_create(ui_CONFIG);
    lv_obj_set_width(ui_btnConfig2, lv_pct(10));
    lv_obj_set_height(ui_btnConfig2, lv_pct(15));
    lv_obj_set_x(ui_btnConfig2, lv_pct(-1));
    lv_obj_set_y(ui_btnConfig2, lv_pct(0));
    lv_obj_set_align(ui_btnConfig2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnConfig2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConfig2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnConfig2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConfig2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnConfig2, &ui_img_icn_x2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNetTittle = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblNetTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNetTittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNetTittle, -157);
    lv_obj_set_y(ui_lblNetTittle, lv_pct(-43));
    lv_obj_set_align(ui_lblNetTittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNetTittle, "RED");
    lv_obj_set_style_text_color(ui_lblNetTittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNetTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passArea = lv_textarea_create(ui_CONFIG);
    lv_obj_set_width(ui_passArea, 250);
    lv_obj_set_height(ui_passArea, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_passArea, 0);
    lv_obj_set_y(ui_passArea, lv_pct(-27));
    lv_obj_set_align(ui_passArea, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_passArea, true);
    lv_textarea_set_password_mode(ui_passArea, true);
    lv_obj_set_style_text_font(ui_passArea, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_imgWifi2 = lv_img_create(ui_CONFIG);
    lv_img_set_src(ui_imgWifi2, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_imgWifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWifi2, lv_pct(2));
    lv_obj_set_y(ui_imgWifi2, lv_pct(2));
    lv_obj_add_flag(ui_imgWifi2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_imgWifi2, lv_color_hex(0x525552), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgWifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_llblPswTittle = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_llblPswTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_llblPswTittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_llblPswTittle, -167);
    lv_obj_set_y(ui_llblPswTittle, lv_pct(-27));
    lv_obj_set_align(ui_llblPswTittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_llblPswTittle, "CLAVE");
    lv_obj_set_style_text_color(ui_llblPswTittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_llblPswTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNetworkIP = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblNetworkIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNetworkIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNetworkIP, lv_pct(2));
    lv_obj_set_y(ui_lblNetworkIP, lv_pct(-24));
    lv_obj_set_align(ui_lblNetworkIP, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblNetworkIP, "");
    lv_obj_set_style_text_color(ui_lblNetworkIP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNetworkIP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFirmwareVersion = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblFirmwareVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFirmwareVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFirmwareVersion, lv_pct(2));
    lv_obj_set_y(ui_lblFirmwareVersion, lv_pct(-17));
    lv_obj_set_align(ui_lblFirmwareVersion, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblFirmwareVersion, "");
    lv_obj_set_style_text_color(ui_lblFirmwareVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblFirmwareVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNumMaquina = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblNumMaquina, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNumMaquina, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNumMaquina, lv_pct(2));
    lv_obj_set_y(ui_lblNumMaquina, lv_pct(-10));
    lv_obj_set_align(ui_lblNumMaquina, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblNumMaquina, "");
    lv_obj_set_style_text_color(ui_lblNumMaquina, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNumMaquina, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOdoMaquina = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblOdoMaquina, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOdoMaquina, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOdoMaquina, lv_pct(2));
    lv_obj_set_y(ui_lblOdoMaquina, lv_pct(-3));
    lv_obj_set_align(ui_lblOdoMaquina, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblOdoMaquina, "");
    lv_obj_set_style_text_color(ui_lblOdoMaquina, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOdoMaquina, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnConectWifi = lv_btn_create(ui_CONFIG);
    lv_obj_set_height(ui_btnConectWifi, 50);
    lv_obj_set_width(ui_btnConectWifi, lv_pct(30));
    lv_obj_set_x(ui_btnConectWifi, lv_pct(-25));
    lv_obj_set_y(ui_btnConectWifi, lv_pct(5));
    lv_obj_set_align(ui_btnConectWifi, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btnConectWifi, lv_color_hex(0x006F06), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConectWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnConectWifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnConectWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnConectWifi, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnDisconectWifi1 = lv_btn_create(ui_CONFIG);
    lv_obj_set_height(ui_btnDisconectWifi1, 50);
    lv_obj_set_width(ui_btnDisconectWifi1, lv_pct(30));
    lv_obj_set_x(ui_btnDisconectWifi1, lv_pct(25));
    lv_obj_set_y(ui_btnDisconectWifi1, lv_pct(6));
    lv_obj_set_align(ui_btnDisconectWifi1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_btnDisconectWifi1, lv_color_hex(0xB85A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDisconectWifi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnDisconectWifi1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblbtnConectar = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblbtnConectar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblbtnConectar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblbtnConectar, lv_pct(-25));
    lv_obj_set_y(ui_lblbtnConectar, lv_pct(5));
    lv_obj_set_align(ui_lblbtnConectar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblbtnConectar, "CONECTAR");
    lv_obj_set_style_text_color(ui_lblbtnConectar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblbtnConectar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblbtnDesconectar = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblbtnDesconectar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblbtnDesconectar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblbtnDesconectar, lv_pct(25));
    lv_obj_set_y(ui_lblbtnDesconectar, lv_pct(6));
    lv_obj_set_align(ui_lblbtnDesconectar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblbtnDesconectar, "DESCONECTAR");
    lv_obj_set_style_text_color(ui_lblbtnDesconectar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblbtnDesconectar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfo = lv_label_create(ui_CONFIG);
    lv_obj_set_width(ui_lblInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblInfo, lv_pct(0));
    lv_obj_set_y(ui_lblInfo, lv_pct(-15));
    lv_obj_set_align(ui_lblInfo, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfo, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lblInfo, "");
    lv_obj_set_style_text_color(ui_lblInfo, lv_color_hex(0x00FF21), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_CONFIG);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_height(ui_Keyboard1, lv_pct(60));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_btnConfig2, ui_event_btnConfig2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passArea, ui_event_passArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnConectWifi, ui_event_btnConectWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnDisconectWifi1, ui_event_btnDisconectWifi1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_passArea);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CONFIG, ui_event_CONFIG, LV_EVENT_ALL, NULL);

}
