// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#include "../ui.h"

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_HOME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HOME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HOME, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HOME, 13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBg = lv_img_create(ui_HOME);
    lv_img_set_src(ui_imgBg, &ui_img_bg1_png);
    lv_obj_set_width(ui_imgBg, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_imgBg, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_imgBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgBg, 345);

    ui_Group_Gauge = lv_obj_create(ui_HOME);
    lv_obj_remove_style_all(ui_Group_Gauge);
    lv_obj_set_width(ui_Group_Gauge, lv_pct(60));
    lv_obj_set_height(ui_Group_Gauge, lv_pct(100));
    lv_obj_set_x(ui_Group_Gauge, lv_pct(-1));
    lv_obj_set_y(ui_Group_Gauge, lv_pct(0));
    lv_obj_set_align(ui_Group_Gauge, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Group_Gauge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgGaugeSpeed = lv_img_create(ui_Group_Gauge);
    lv_img_set_src(ui_imgGaugeSpeed, &ui_img_gauge_velocidad_png);
    lv_obj_set_width(ui_imgGaugeSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgGaugeSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgGaugeSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgGaugeSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgGaugeSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgGaugeSpeed, 350);

    ui_imgCursorSpeed = lv_img_create(ui_Group_Gauge);
    lv_img_set_src(ui_imgCursorSpeed, &ui_img_speed_indicator_png);
    lv_obj_set_width(ui_imgCursorSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgCursorSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgCursorSpeed, lv_pct(0));
    lv_obj_set_y(ui_imgCursorSpeed, lv_pct(3));
    lv_obj_set_align(ui_imgCursorSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgCursorSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgCursorSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgCursorSpeed, 400);

    ui_Group_Speed = lv_obj_create(ui_Group_Gauge);
    lv_obj_remove_style_all(ui_Group_Speed);
    lv_obj_set_width(ui_Group_Speed, lv_pct(100));
    lv_obj_set_height(ui_Group_Speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Group_Speed, lv_pct(0));
    lv_obj_set_y(ui_Group_Speed, lv_pct(-10));
    lv_obj_set_align(ui_Group_Speed, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Speed, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Speed, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Group_Speed);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -3);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblSpeedUnit = lv_label_create(ui_Container1);
    lv_obj_set_height(ui_lblSpeedUnit, 25);
    lv_obj_set_width(ui_lblSpeedUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lblSpeedUnit, lv_pct(-16));
    lv_obj_set_y(ui_lblSpeedUnit, lv_pct(-19));
    lv_obj_set_align(ui_lblSpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeedUnit, "km/h");
    lv_obj_set_style_text_color(ui_lblSpeedUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSpeedUnit, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSpeedNumber = lv_label_create(ui_Group_Speed);
    lv_obj_set_width(ui_lblSpeedNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSpeedNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSpeedNumber, lv_pct(-20));
    lv_obj_set_y(ui_lblSpeedNumber, lv_pct(-1));
    lv_obj_set_align(ui_lblSpeedNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeedNumber, "0.0");
    lv_obj_set_style_text_color(ui_lblSpeedNumber, lv_color_hex(0xFFBF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSpeedNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSpeedNumber, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSpeedNumber, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Ritmo = lv_obj_create(ui_Group_Gauge);
    lv_obj_remove_style_all(ui_Group_Ritmo);
    lv_obj_set_width(ui_Group_Ritmo, lv_pct(100));
    lv_obj_set_height(ui_Group_Ritmo, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Group_Ritmo, lv_pct(0));
    lv_obj_set_y(ui_Group_Ritmo, lv_pct(23));
    lv_obj_set_align(ui_Group_Ritmo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Ritmo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Ritmo, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Ritmo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVarRitm = lv_label_create(ui_Group_Ritmo);
    lv_obj_set_width(ui_LabelVarRitm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarRitm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVarRitm, lv_pct(-37));
    lv_obj_set_y(ui_LabelVarRitm, lv_pct(37));
    lv_obj_set_align(ui_LabelVarRitm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVarRitm, "00'00\"");
    lv_obj_set_style_text_color(ui_LabelVarRitm, lv_color_hex(0xE3FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarRitm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarRitm, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_kmh4 = lv_label_create(ui_Group_Ritmo);
    lv_obj_set_width(ui_Label_kmh4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_kmh4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_kmh4, lv_pct(-15));
    lv_obj_set_y(ui_Label_kmh4, lv_pct(45));
    lv_obj_set_align(ui_Label_kmh4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_kmh4, "min/km");
    lv_obj_set_style_text_color(ui_Label_kmh4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_kmh4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_kmh4, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Right_Side = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Group_Right_Side, lv_pct(50));
    lv_obj_set_height(ui_Group_Right_Side, lv_pct(80));
    lv_obj_set_x(ui_Group_Right_Side, 0);
    lv_obj_set_y(ui_Group_Right_Side, lv_pct(-3));
    lv_obj_set_align(ui_Group_Right_Side, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Group_Right_Side, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Right_Side, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Right_Side, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Real_Time2 = lv_obj_create(ui_Group_Right_Side);
    lv_obj_set_width(ui_Group_Real_Time2, lv_pct(100));
    lv_obj_set_height(ui_Group_Real_Time2, lv_pct(100));
    lv_obj_set_align(ui_Group_Real_Time2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Group_Real_Time2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Real_Time2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Real_Time2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Real_Time2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Real_Time2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Data_Inter = lv_obj_create(ui_Group_Real_Time2);
    lv_obj_set_width(ui_Group_Data_Inter, lv_pct(100));
    lv_obj_set_height(ui_Group_Data_Inter, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Group_Data_Inter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Data_Inter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Data_Inter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Data_Inter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Data_Inter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Data_Inter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInterTittle = lv_label_create(ui_Group_Data_Inter);
    lv_obj_set_width(ui_lblInterTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblInterTittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblInterTittle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblInterTittle, "ENTRENA LIBRE");
    lv_obj_set_style_text_color(ui_lblInterTittle, lv_color_hex(0xF3B100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInterTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblInterTittle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInterTittle, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupPtllEntrenaInter2 = lv_obj_create(ui_Group_Data_Inter);
    lv_obj_remove_style_all(ui_groupPtllEntrenaInter2);
    lv_obj_set_width(ui_groupPtllEntrenaInter2, lv_pct(100));
    lv_obj_set_height(ui_groupPtllEntrenaInter2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_groupPtllEntrenaInter2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupPtllEntrenaInter2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblTittleTipoPasada2 = lv_label_create(ui_groupPtllEntrenaInter2);
    lv_obj_set_width(ui_lblTittleTipoPasada2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleTipoPasada2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTittleTipoPasada2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleTipoPasada2, "por TIEMPO");
    lv_obj_set_style_text_color(ui_lblTittleTipoPasada2, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleTipoPasada2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleTipoPasada2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleTipoPasada2, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupPtllEntrenaInter = lv_obj_create(ui_Group_Data_Inter);
    lv_obj_set_width(ui_groupPtllEntrenaInter, lv_pct(60));
    lv_obj_set_height(ui_groupPtllEntrenaInter, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_groupPtllEntrenaInter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupPtllEntrenaInter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_groupPtllEntrenaInter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupPtllEntrenaInter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_groupPtllEntrenaInter);
    lv_obj_set_width(ui_Panel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Panel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_x(ui_Panel3, lv_pct(1));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Series = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Series, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Series, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Series, lv_pct(-15));
    lv_obj_set_y(ui_Series, lv_pct(0));
    lv_label_set_text(ui_Series, "Series: ");
    lv_obj_set_style_text_color(ui_Series, lv_color_hex(0xFF4500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Series, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Series, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pasadas = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Pasadas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pasadas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pasadas, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Pasadas, "Pasadas:    ");
    lv_obj_set_style_text_color(ui_Pasadas, lv_color_hex(0x3CD000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pasadas, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_groupPtllEntrenaInter);
    lv_obj_set_width(ui_Panel4, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Panel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_x(ui_Panel4, lv_pct(29));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblNumSeries = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lblNumSeries, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNumSeries, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNumSeries, 0);
    lv_obj_set_y(ui_lblNumSeries, -18);
    lv_obj_set_align(ui_lblNumSeries, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNumSeries, "0");
    lv_obj_set_style_text_color(ui_lblNumSeries, lv_color_hex(0xDE3C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNumSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNumSeries, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblNumPasadas = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblNumPasadas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNumPasadas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblNumPasadas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNumPasadas, "0");
    lv_obj_set_style_text_color(ui_lblNumPasadas, lv_color_hex(0x39D200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblNumPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblNumPasadas, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Distance = lv_obj_create(ui_Group_Real_Time2);
    lv_obj_set_width(ui_Group_Distance, lv_pct(100));
    lv_obj_set_height(ui_Group_Distance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Group_Distance, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Distance, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Distance, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Distance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Distance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Distance, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistanceTittle = lv_label_create(ui_Group_Distance);
    lv_obj_set_width(ui_lblDistanceTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDistanceTittle, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_align(ui_lblDistanceTittle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblDistanceTittle, "DISTANCIA");
    lv_obj_set_style_text_color(ui_lblDistanceTittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceTittle, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Group_Distance);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistanceNumber = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblDistanceNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDistanceNumber, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_lblDistanceNumber, lv_pct(-10));
    lv_obj_set_y(ui_lblDistanceNumber, lv_pct(10));
    lv_obj_set_align(ui_lblDistanceNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDistanceNumber, "0");
    lv_obj_set_style_text_color(ui_lblDistanceNumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceNumber, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel2, lv_pct(30));
    lv_obj_set_height(ui_Panel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistanceUnit = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblDistanceUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDistanceUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDistanceUnit, lv_pct(60));
    lv_obj_set_y(ui_lblDistanceUnit, lv_pct(30));
    lv_label_set_text(ui_lblDistanceUnit, "mt");
    lv_obj_set_style_text_color(ui_lblDistanceUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDistanceUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDistanceUnit, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Time = lv_obj_create(ui_Group_Real_Time2);
    lv_obj_set_width(ui_Group_Time, lv_pct(100));
    lv_obj_set_height(ui_Group_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Group_Time, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Group_Time, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Group_Time, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Group_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeTittle = lv_label_create(ui_Group_Time);
    lv_obj_set_width(ui_lblTimeTittle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTimeTittle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTimeTittle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTimeTittle, "TIEMPO");
    lv_obj_set_style_text_color(ui_lblTimeTittle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimeTittle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTimeTittle, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeNumber = lv_label_create(ui_Group_Time);
    lv_obj_set_width(ui_lblTimeNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTimeNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTimeNumber, lv_pct(0));
    lv_obj_set_y(ui_lblTimeNumber, lv_pct(10));
    lv_obj_set_align(ui_lblTimeNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTimeNumber, "00:00:00");
    lv_obj_set_style_text_color(ui_lblTimeNumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTimeNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTimeNumber, &ui_font_Big_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Header_Up = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Group_Header_Up, lv_pct(100));
    lv_obj_set_height(ui_Group_Header_Up, lv_pct(20));
    lv_obj_set_x(ui_Group_Header_Up, lv_pct(0));
    lv_obj_set_y(ui_Group_Header_Up, lv_pct(-5));
    lv_obj_set_align(ui_Group_Header_Up, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Group_Header_Up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Header_Up, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Header_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBgGroupSettingsUp = lv_img_create(ui_Group_Header_Up);
    lv_img_set_src(ui_imgBgGroupSettingsUp, &ui_img_settings_up_png);
    lv_obj_set_width(ui_imgBgGroupSettingsUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBgGroupSettingsUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBgGroupSettingsUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBgGroupSettingsUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBgGroupSettingsUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgBgGroupSettingsUp, 310);

    ui_imgWifi = lv_img_create(ui_Group_Header_Up);
    lv_img_set_src(ui_imgWifi, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_imgWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWifi, lv_pct(-45));
    lv_obj_set_y(ui_imgWifi, lv_pct(4));
    lv_obj_set_align(ui_imgWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgWifi, 400);
    lv_obj_set_style_img_recolor(ui_imgWifi, lv_color_hex(0x525552), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblNetName = lv_label_create(ui_Group_Header_Up);
    lv_obj_set_width(ui_lblNetName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblNetName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblNetName, lv_pct(-29));
    lv_obj_set_y(ui_lblNetName, lv_pct(-5));
    lv_obj_set_align(ui_lblNetName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblNetName, "");
    lv_obj_set_style_text_font(ui_lblNetName, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDate = lv_label_create(ui_Group_Header_Up);
    lv_obj_set_width(ui_lblDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDate, lv_pct(0));
    lv_obj_set_y(ui_lblDate, lv_pct(-5));
    lv_obj_set_align(ui_lblDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDate, "");
    lv_obj_set_style_text_color(ui_lblDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDate, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime = lv_label_create(ui_Group_Header_Up);
    lv_obj_set_width(ui_lblTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTime, lv_pct(33));
    lv_obj_set_y(ui_lblTime, lv_pct(-5));
    lv_obj_set_align(ui_lblTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime, "");
    lv_obj_set_style_text_color(ui_lblTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnConfig = lv_btn_create(ui_Group_Header_Up);
    lv_obj_set_width(ui_btnConfig, lv_pct(10));
    lv_obj_set_height(ui_btnConfig, lv_pct(100));
    lv_obj_set_x(ui_btnConfig, lv_pct(1));
    lv_obj_set_y(ui_btnConfig, lv_pct(7));
    lv_obj_set_align(ui_btnConfig, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnConfig, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig, lv_color_hex(0xFFBF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnConfig, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig, lv_color_hex(0xFF0303), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_btnConfig, &ui_img_icn_settings_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_btnConfig, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_btnConfig, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Group_Settings_Down = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Group_Settings_Down, lv_pct(100));
    lv_obj_set_height(ui_Group_Settings_Down, lv_pct(20));
    lv_obj_set_x(ui_Group_Settings_Down, lv_pct(0));
    lv_obj_set_y(ui_Group_Settings_Down, lv_pct(3));
    lv_obj_set_align(ui_Group_Settings_Down, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Group_Settings_Down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Settings_Down, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Settings_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBgGroupSettingsDown = lv_img_create(ui_Group_Settings_Down);
    lv_img_set_src(ui_imgBgGroupSettingsDown, &ui_img_settings_down_png);
    lv_obj_set_width(ui_imgBgGroupSettingsDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBgGroupSettingsDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgBgGroupSettingsDown, 0);
    lv_obj_set_y(ui_imgBgGroupSettingsDown, 4);
    lv_obj_set_align(ui_imgBgGroupSettingsDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBgGroupSettingsDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBgGroupSettingsDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgBgGroupSettingsDown, 350);

    ui_Button_Group = lv_obj_create(ui_Group_Settings_Down);
    lv_obj_set_width(ui_Button_Group, lv_pct(41));
    lv_obj_set_height(ui_Button_Group, lv_pct(79));
    lv_obj_set_align(ui_Button_Group, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_Button_Group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button_Group, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button_Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRealTime = lv_btn_create(ui_Button_Group);
    lv_obj_set_width(ui_btnRealTime, lv_pct(45));
    lv_obj_set_height(ui_btnRealTime, lv_pct(80));
    lv_obj_set_align(ui_btnRealTime, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_btnRealTime, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_btnRealTime, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnRealTime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnRealTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRealTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnRealTime, &ui_img_icn_run_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRealTime, lv_color_hex(0xE7A02F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRealTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRealTime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnRealTime, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRealTime, lv_color_hex(0xFF9600), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnRealTime, 150, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_btnInter = lv_btn_create(ui_Button_Group);
    lv_obj_set_width(ui_btnInter, lv_pct(45));
    lv_obj_set_height(ui_btnInter, lv_pct(80));
    lv_obj_set_x(ui_btnInter, 0);
    lv_obj_set_y(ui_btnInter, -1);
    lv_obj_set_align(ui_btnInter, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnInter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnInter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnInter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnInter, &ui_img_icn_clock_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnInter, lv_color_hex(0xE7A02F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnInter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnInter, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnInter, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnInter, lv_color_hex(0xFF9600), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnInter, 150, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_groupReinitbtn = lv_obj_create(ui_Group_Settings_Down);
    lv_obj_remove_style_all(ui_groupReinitbtn);
    lv_obj_set_width(ui_groupReinitbtn, lv_pct(60));
    lv_obj_set_height(ui_groupReinitbtn, lv_pct(79));
    lv_obj_set_align(ui_groupReinitbtn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_groupReinitbtn, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupReinitbtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnReinicio = lv_btn_create(ui_groupReinitbtn);
    lv_obj_set_width(ui_btnReinicio, lv_pct(75));
    lv_obj_set_height(ui_btnReinicio, lv_pct(70));
    lv_obj_set_align(ui_btnReinicio, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnReinicio, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnReinicio, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnReinicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnReinicio, lv_color_hex(0xDC9D29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnReinicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnReinicio, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblReiniciobtn = lv_label_create(ui_groupReinitbtn);
    lv_obj_set_width(ui_lblReiniciobtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblReiniciobtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblReiniciobtn, -3);
    lv_obj_set_y(ui_lblReiniciobtn, 1);
    lv_obj_set_align(ui_lblReiniciobtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblReiniciobtn, "REINICIAR ENTRENAMIENTO");
    lv_obj_set_style_text_color(ui_lblReiniciobtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblReiniciobtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblReiniciobtn, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupPausa = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_groupPausa, lv_pct(50));
    lv_obj_set_height(ui_groupPausa, lv_pct(50));
    lv_obj_set_align(ui_groupPausa, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_groupPausa, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupPausa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_groupPausa, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_groupPausa, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupPausa, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_groupPausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_groupPausa, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_groupPausa, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTittlePausa = lv_label_create(ui_groupPausa);
    lv_obj_set_width(ui_lblTittlePausa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittlePausa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittlePausa, 0);
    lv_obj_set_y(ui_lblTittlePausa, 12);
    lv_obj_set_align(ui_lblTittlePausa, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittlePausa, "PAUSA");
    lv_obj_set_style_text_color(ui_lblTittlePausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittlePausa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittlePausa, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPausa = lv_label_create(ui_groupPausa);
    lv_obj_set_width(ui_lblPausa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPausa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPausa, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPausa, "0");
    lv_obj_set_style_text_color(ui_lblPausa, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPausa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPausa, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_HOME);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 100);
    lv_obj_set_height(ui_Container5, 50);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnConfig, ui_event_btnConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRealTime, ui_event_btnRealTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnInter, ui_event_btnInter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnReinicio, ui_event_btnReinicio, LV_EVENT_ALL, NULL);

}
