// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_new7

#ifndef UI_INICIO_H
#define UI_INICIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_INICIO
extern void ui_INICIO_screen_init(void);
extern void ui_INICIO_screen_destroy(void);
extern void ui_event_INICIO(lv_event_t * e);
extern lv_obj_t * ui_INICIO;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_otaOverlay;
extern lv_obj_t * ui_lblOtaStatus;
extern lv_obj_t * ui_barOta;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

