// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: willi_new7

#include "../ui.h"

lv_obj_t * ui_INICIO = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_otaOverlay = NULL;
lv_obj_t * ui_lblOtaStatus = NULL;
lv_obj_t * ui_barOta = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_INICIO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_HOME, LV_SCR_LOAD_ANIM_FADE_OUT, 250, 5000, &ui_HOME_screen_init);
    }
}

// build funtions

void ui_INICIO_screen_init(void)
{
    ui_INICIO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_INICIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_INICIO, lv_color_hex(0x4AA44A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_INICIO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_INICIO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_INICIO, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_INICIO);
    lv_img_set_src(ui_Image1, &ui_img_logoj2f_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 350);

    ui_otaOverlay = lv_obj_create(ui_INICIO);
    lv_obj_set_width(ui_otaOverlay, lv_pct(75));
    lv_obj_set_height(ui_otaOverlay, lv_pct(25));
    lv_obj_set_align(ui_otaOverlay, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_otaOverlay, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_otaOverlay, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_otaOverlay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_otaOverlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_otaOverlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_otaOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblOtaStatus = lv_label_create(ui_otaOverlay);
    lv_obj_set_width(ui_lblOtaStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOtaStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOtaStatus, 0);
    lv_obj_set_y(ui_lblOtaStatus, 8);
    lv_obj_set_align(ui_lblOtaStatus, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_color(ui_lblOtaStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblOtaStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblOtaStatus, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barOta = lv_bar_create(ui_otaOverlay);
    lv_bar_set_value(ui_barOta, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barOta, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barOta, lv_pct(75));
    lv_obj_set_height(ui_barOta, lv_pct(25));
    lv_obj_set_align(ui_barOta, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barOta, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barOta, lv_color_hex(0x949494), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barOta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barOta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barOta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barOta, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_barOta, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barOta, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_otaOverlay);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "%");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_INICIO, ui_event_INICIO, LV_EVENT_ALL, NULL);

}

void ui_INICIO_screen_destroy(void)
{
    if(ui_INICIO) lv_obj_del(ui_INICIO);

    // NULL screen variables
    ui_INICIO = NULL;
    ui_Image1 = NULL;
    ui_otaOverlay = NULL;
    ui_lblOtaStatus = NULL;
    ui_barOta = NULL;
    ui_Label1 = NULL;

}
