// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#include "../ui.h"

void ui_PROGRAMADO_screen_init(void)
{
    ui_PROGRAMADO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PROGRAMADO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_PROGRAMADO, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PROGRAMADO, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_PROGRAMADO, lv_color_hex(0x314831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PROGRAMADO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupSeries = lv_obj_create(ui_PROGRAMADO);
    lv_obj_set_width(ui_groupSeries, lv_pct(100));
    lv_obj_set_height(ui_groupSeries, lv_pct(85));
    lv_obj_set_align(ui_groupSeries, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_groupSeries, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_groupSeries, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_groupSeries, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTittleSeries = lv_label_create(ui_groupSeries);
    lv_obj_set_width(ui_lblTittleSeries, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries, lv_pct(0));
    lv_obj_set_y(ui_lblTittleSeries, lv_pct(2));
    lv_obj_set_align(ui_lblTittleSeries, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries, "SERIES");
    lv_obj_set_style_text_color(ui_lblTittleSeries, lv_color_hex(0xFBAD30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_lblTittleSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_lblTittleSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerNumSeries = lv_roller_create(ui_groupSeries);
    lv_roller_set_options(ui_rollerNumSeries, "1\n2\n3\n4\n5", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollerNumSeries, lv_pct(20));
    lv_obj_set_height(ui_rollerNumSeries, lv_pct(65));
    lv_obj_set_x(ui_rollerNumSeries, lv_pct(-15));
    lv_obj_set_y(ui_rollerNumSeries, lv_pct(-5));
    lv_obj_set_align(ui_rollerNumSeries, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_letter_space(ui_rollerNumSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerNumSeries, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerNumSeries, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerNumSeries, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerNumSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerNumSeries, lv_color_hex(0x002C10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerNumSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerNumSeries, lv_color_hex(0xD98200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerNumSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerNumSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerNumSeries, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerNumSeries, lv_color_hex(0xFFC900), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerNumSeries, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerNumSeries, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerNumSeries, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerNumSeries, 5, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerNumSeries, lv_color_hex(0x004E22), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerNumSeries, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rollerNumSeries, lv_color_hex(0x004C20), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rollerNumSeries, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerNumSeries, 5, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_rollerNumSeries, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_lblTittlePausaSeries = lv_label_create(ui_groupSeries);
    lv_obj_set_width(ui_lblTittlePausaSeries, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittlePausaSeries, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittlePausaSeries, lv_pct(15));
    lv_obj_set_y(ui_lblTittlePausaSeries, lv_pct(-31));
    lv_obj_set_align(ui_lblTittlePausaSeries, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTittlePausaSeries, "PAUSA");
    lv_obj_set_style_text_color(ui_lblTittlePausaSeries, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittlePausaSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittlePausaSeries, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUnitPauseSeries = lv_label_create(ui_groupSeries);
    lv_obj_set_width(ui_lblUnitPauseSeries, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUnitPauseSeries, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnitPauseSeries, lv_pct(15));
    lv_obj_set_y(ui_lblUnitPauseSeries, lv_pct(-24));
    lv_obj_set_align(ui_lblUnitPauseSeries, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnitPauseSeries, "(min)");
    lv_obj_set_style_text_color(ui_lblUnitPauseSeries, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblUnitPauseSeries, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblUnitPauseSeries, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerMacropausa = lv_roller_create(ui_groupSeries);
    lv_roller_set_options(ui_rollerMacropausa, "1 \n2 \n3 \n4 \n5 \n6 ", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollerMacropausa, lv_pct(20));
    lv_obj_set_height(ui_rollerMacropausa, lv_pct(65));
    lv_obj_set_x(ui_rollerMacropausa, lv_pct(15));
    lv_obj_set_y(ui_rollerMacropausa, lv_pct(-5));
    lv_obj_set_align(ui_rollerMacropausa, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_letter_space(ui_rollerMacropausa, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerMacropausa, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerMacropausa, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMacropausa, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMacropausa, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMacropausa, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMacropausa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerMacropausa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerMacropausa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerMacropausa, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerMacropausa, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerMacropausa, lv_color_hex(0xA50000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMacropausa, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMacropausa, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMacropausa, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rollerMacropausa, lv_color_hex(0x9C9D9C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rollerMacropausa, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerMacropausa, 5, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_rollerMacropausa, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_lblTittleSeries2 = lv_label_create(ui_groupSeries);
    lv_obj_set_width(ui_lblTittleSeries2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries2, lv_pct(-15));
    lv_obj_set_y(ui_lblTittleSeries2, lv_pct(17));
    lv_obj_set_align(ui_lblTittleSeries2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries2, "Cantidad");
    lv_obj_set_style_text_color(ui_lblTittleSeries2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries2, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRightToPasadas = lv_btn_create(ui_groupSeries);
    lv_obj_set_width(ui_btnRightToPasadas, lv_pct(15));
    lv_obj_set_height(ui_btnRightToPasadas, lv_pct(100));
    lv_obj_set_align(ui_btnRightToPasadas, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btnRightToPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRightToPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnRightToPasadas, &ui_img_icn_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRightToPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnRightToPasadas, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRightToPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnRightToPasadas, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRightToPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnRightToPasadas, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_btnLeftToTipoPasadas = lv_btn_create(ui_groupSeries);
    lv_obj_set_width(ui_btnLeftToTipoPasadas, lv_pct(15));
    lv_obj_set_height(ui_btnLeftToTipoPasadas, lv_pct(100));
    lv_obj_set_align(ui_btnLeftToTipoPasadas, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btnLeftToTipoPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnLeftToTipoPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnLeftToTipoPasadas, &ui_img_icn_arrow_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnLeftToTipoPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnLeftToTipoPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnLeftToTipoPasadas, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblTittleSeries1 = lv_label_create(ui_groupSeries);
    lv_obj_set_width(ui_lblTittleSeries1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries1, lv_pct(-43));
    lv_obj_set_y(ui_lblTittleSeries1, lv_pct(67));
    lv_obj_set_align(ui_lblTittleSeries1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries1, "Config.\nTIPO\nDE\nPASADA");
    lv_obj_set_style_text_color(ui_lblTittleSeries1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleSeries1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries1, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTittleSeries3 = lv_label_create(ui_groupSeries);
    lv_obj_set_width(ui_lblTittleSeries3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries3, lv_pct(43));
    lv_obj_set_y(ui_lblTittleSeries3, lv_pct(73));
    lv_obj_set_align(ui_lblTittleSeries3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries3, "Config.\nPASADA");
    lv_obj_set_style_text_color(ui_lblTittleSeries3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleSeries3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries3, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Buttons = lv_obj_create(ui_PROGRAMADO);
    lv_obj_set_width(ui_Group_Buttons, lv_pct(100));
    lv_obj_set_height(ui_Group_Buttons, lv_pct(15));
    lv_obj_set_x(ui_Group_Buttons, lv_pct(2));
    lv_obj_set_y(ui_Group_Buttons, lv_pct(2));
    lv_obj_set_align(ui_Group_Buttons, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Group_Buttons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Group_Buttons, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Buttons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Buttons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroupOk = lv_obj_create(ui_Group_Buttons);
    lv_obj_set_width(ui_GroupOk, lv_pct(50));
    lv_obj_set_height(ui_GroupOk, lv_pct(90));
    lv_obj_set_align(ui_GroupOk, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GroupOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GroupOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GroupOk, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnOk = lv_btn_create(ui_GroupOk);
    lv_obj_set_width(ui_btnOk, lv_pct(100));
    lv_obj_set_height(ui_btnOk, lv_pct(100));
    lv_obj_set_align(ui_btnOk, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnOk, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk, lv_color_hex(0x001800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOk, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnOk, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnOk, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk, lv_color_hex(0x00FF1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnOk, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_imgOk = lv_img_create(ui_GroupOk);
    lv_img_set_src(ui_imgOk, &ui_img_icn_ok_png);
    lv_obj_set_width(ui_imgOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgOk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgOk, 600);
    lv_obj_set_style_img_recolor(ui_imgOk, lv_color_hex(0x00FF21), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnRightToPasadas, ui_event_btnRightToPasadas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnLeftToTipoPasadas, ui_event_btnLeftToTipoPasadas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnOk, ui_event_btnOk, LV_EVENT_ALL, NULL);

}
