// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#include "../ui.h"

void ui_PROGRAMADO_2_screen_init(void)
{
    ui_PROGRAMADO_2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PROGRAMADO_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_PROGRAMADO_2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PROGRAMADO_2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_PROGRAMADO_2, lv_color_hex(0x314831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PROGRAMADO_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupPasadas = lv_obj_create(ui_PROGRAMADO_2);
    lv_obj_set_width(ui_groupPasadas, lv_pct(100));
    lv_obj_set_height(ui_groupPasadas, lv_pct(85));
    lv_obj_set_x(ui_groupPasadas, lv_pct(0));
    lv_obj_set_y(ui_groupPasadas, lv_pct(1));
    lv_obj_set_align(ui_groupPasadas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_groupPasadas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_groupPasadas, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_groupPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_groupPasadas);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, lv_pct(18));
    lv_obj_set_y(ui_Label7, lv_pct(13));
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "(seg)");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_groupPasadas);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, lv_pct(-18));
    lv_obj_set_y(ui_Label1, lv_pct(13));
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "(min)");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_groupPasadas);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, lv_pct(0));
    lv_obj_set_y(ui_Label2, lv_pct(30));
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "PAUSA");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerMicropausaSeg = lv_roller_create(ui_groupPasadas);
    lv_roller_set_options(ui_rollerMicropausaSeg, "0\n5\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_rollerMicropausaSeg, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_rollerMicropausaSeg, lv_pct(15));
    lv_obj_set_height(ui_rollerMicropausaSeg, lv_pct(30));
    lv_obj_set_x(ui_rollerMicropausaSeg, lv_pct(18));
    lv_obj_set_y(ui_rollerMicropausaSeg, lv_pct(-2));
    lv_obj_set_align(ui_rollerMicropausaSeg, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_letter_space(ui_rollerMicropausaSeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerMicropausaSeg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerMicropausaSeg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMicropausaSeg, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMicropausaSeg, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMicropausaSeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMicropausaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerMicropausaSeg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerMicropausaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerMicropausaSeg, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerMicropausaSeg, lv_color_hex(0xA50000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMicropausaSeg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMicropausaSeg, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMicropausaSeg, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMicropausaSeg, lv_color_hex(0x9C9D9C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMicropausaSeg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerMicropausaSeg, LV_BORDER_SIDE_FULL, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_groupPasadas);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, lv_pct(0));
    lv_obj_set_y(ui_Label3, lv_pct(1));
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label3, "PASADAS");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFAE31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerMicropausaMin = lv_roller_create(ui_groupPasadas);
    lv_roller_set_options(ui_rollerMicropausaMin, "0\n1 \n2 \n3 ", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollerMicropausaMin, lv_pct(15));
    lv_obj_set_height(ui_rollerMicropausaMin, lv_pct(30));
    lv_obj_set_x(ui_rollerMicropausaMin, lv_pct(-18));
    lv_obj_set_y(ui_rollerMicropausaMin, lv_pct(-2));
    lv_obj_set_align(ui_rollerMicropausaMin, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_letter_space(ui_rollerMicropausaMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerMicropausaMin, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerMicropausaMin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMicropausaMin, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMicropausaMin, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMicropausaMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMicropausaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerMicropausaMin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerMicropausaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerMicropausaMin, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerMicropausaMin, lv_color_hex(0xA50000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMicropausaMin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMicropausaMin, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMicropausaMin, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMicropausaMin, lv_color_hex(0x9C9D9C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMicropausaMin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerMicropausaMin, LV_BORDER_SIDE_FULL, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_rollerNumPasadas = lv_roller_create(ui_groupPasadas);
    lv_roller_set_options(ui_rollerNumPasadas, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollerNumPasadas, lv_pct(50));
    lv_obj_set_height(ui_rollerNumPasadas, lv_pct(40));
    lv_obj_set_x(ui_rollerNumPasadas, lv_pct(0));
    lv_obj_set_y(ui_rollerNumPasadas, lv_pct(15));
    lv_obj_set_align(ui_rollerNumPasadas, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_letter_space(ui_rollerNumPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerNumPasadas, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerNumPasadas, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerNumPasadas, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerNumPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerNumPasadas, lv_color_hex(0x002C10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerNumPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerNumPasadas, lv_color_hex(0xDE8100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerNumPasadas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerNumPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerNumPasadas, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerNumPasadas, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerNumPasadas, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerNumPasadas, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerNumPasadas, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerNumPasadas, 5, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerNumPasadas, lv_color_hex(0x00AE08), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerNumPasadas, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerNumPasadas, LV_BORDER_SIDE_FULL, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rollerNumPasadas, lv_color_hex(0x00AE08), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rollerNumPasadas, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerNumPasadas, 3, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_rollerNumPasadas, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_btnRightToTipoPasadas = lv_btn_create(ui_groupPasadas);
    lv_obj_set_width(ui_btnRightToTipoPasadas, lv_pct(15));
    lv_obj_set_height(ui_btnRightToTipoPasadas, lv_pct(100));
    lv_obj_set_align(ui_btnRightToTipoPasadas, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btnRightToTipoPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRightToTipoPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnRightToTipoPasadas, &ui_img_icn_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRightToTipoPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnRightToTipoPasadas, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRightToTipoPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnRightToTipoPasadas, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRightToTipoPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnRightToTipoPasadas, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_btnLeftToSeries = lv_btn_create(ui_groupPasadas);
    lv_obj_set_width(ui_btnLeftToSeries, lv_pct(15));
    lv_obj_set_height(ui_btnLeftToSeries, lv_pct(100));
    lv_obj_set_align(ui_btnLeftToSeries, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btnLeftToSeries, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnLeftToSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnLeftToSeries, &ui_img_icn_arrow_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnLeftToSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnLeftToSeries, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnLeftToSeries, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblTittleSeries5 = lv_label_create(ui_groupPasadas);
    lv_obj_set_width(ui_lblTittleSeries5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries5, lv_pct(-43));
    lv_obj_set_y(ui_lblTittleSeries5, lv_pct(73));
    lv_obj_set_align(ui_lblTittleSeries5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries5, "Config.\nSERIES");
    lv_obj_set_style_text_color(ui_lblTittleSeries5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleSeries5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries5, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTittleSeries6 = lv_label_create(ui_groupPasadas);
    lv_obj_set_width(ui_lblTittleSeries6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries6, lv_pct(43));
    lv_obj_set_y(ui_lblTittleSeries6, lv_pct(67));
    lv_obj_set_align(ui_lblTittleSeries6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries6, "Config.\nTIPO\nDE\nPASADA");
    lv_obj_set_style_text_color(ui_lblTittleSeries6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleSeries6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries6, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Buttons2 = lv_obj_create(ui_PROGRAMADO_2);
    lv_obj_set_width(ui_Group_Buttons2, lv_pct(100));
    lv_obj_set_height(ui_Group_Buttons2, lv_pct(15));
    lv_obj_set_x(ui_Group_Buttons2, lv_pct(2));
    lv_obj_set_y(ui_Group_Buttons2, lv_pct(2));
    lv_obj_set_align(ui_Group_Buttons2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Group_Buttons2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Group_Buttons2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Buttons2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Buttons2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Buttons2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroupOk2 = lv_obj_create(ui_Group_Buttons2);
    lv_obj_set_width(ui_GroupOk2, lv_pct(50));
    lv_obj_set_height(ui_GroupOk2, lv_pct(90));
    lv_obj_set_align(ui_GroupOk2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GroupOk2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GroupOk2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GroupOk2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GroupOk2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_GroupOk2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_btnOk2 = lv_btn_create(ui_GroupOk2);
    lv_obj_set_width(ui_btnOk2, lv_pct(100));
    lv_obj_set_height(ui_btnOk2, lv_pct(100));
    lv_obj_set_align(ui_btnOk2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnOk2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk2, lv_color_hex(0x001800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOk2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnOk2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnOk2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnOk2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk2, lv_color_hex(0x00FF1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnOk2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_imgOk2 = lv_img_create(ui_GroupOk2);
    lv_img_set_src(ui_imgOk2, &ui_img_icn_ok_png);
    lv_obj_set_width(ui_imgOk2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgOk2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgOk2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgOk2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgOk2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgOk2, 600);
    lv_obj_set_style_img_recolor(ui_imgOk2, lv_color_hex(0x00FF21), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgOk2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnRightToTipoPasadas, ui_event_btnRightToTipoPasadas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnLeftToSeries, ui_event_btnLeftToSeries, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnOk2, ui_event_btnOk2, LV_EVENT_ALL, NULL);

}
