// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: willi_new7

#include "../ui.h"

void ui_PROGRAMADO_3_screen_init(void)
{
    ui_PROGRAMADO_3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PROGRAMADO_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_PROGRAMADO_3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PROGRAMADO_3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_PROGRAMADO_3, lv_color_hex(0x314831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PROGRAMADO_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupTipoPasadas = lv_obj_create(ui_PROGRAMADO_3);
    lv_obj_set_width(ui_groupTipoPasadas, lv_pct(100));
    lv_obj_set_height(ui_groupTipoPasadas, lv_pct(85));
    lv_obj_set_align(ui_groupTipoPasadas, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_groupTipoPasadas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_groupTipoPasadas, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_groupTipoPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupTipoPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_groupTipoPasadaTiempo = lv_obj_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_groupTipoPasadaTiempo, lv_pct(100));
    lv_obj_set_height(ui_groupTipoPasadaTiempo, lv_pct(50));
    lv_obj_set_align(ui_groupTipoPasadaTiempo, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_groupTipoPasadaTiempo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_groupTipoPasadaTiempo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupTipoPasadaTiempo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUnitTittlePasadaSeg = lv_label_create(ui_groupTipoPasadaTiempo);
    lv_obj_set_width(ui_lblUnitTittlePasadaSeg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUnitTittlePasadaSeg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnitTittlePasadaSeg, lv_pct(15));
    lv_obj_set_y(ui_lblUnitTittlePasadaSeg, lv_pct(-46));
    lv_obj_set_align(ui_lblUnitTittlePasadaSeg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnitTittlePasadaSeg, "(seg)");
    lv_obj_set_style_text_color(ui_lblUnitTittlePasadaSeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblUnitTittlePasadaSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblUnitTittlePasadaSeg, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerPasadaTiempoSeg = lv_roller_create(ui_groupTipoPasadaTiempo);
    lv_roller_set_options(ui_rollerPasadaTiempoSeg, "0\n10\n20\n30\n40\n50", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_rollerPasadaTiempoSeg, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_rollerPasadaTiempoSeg, lv_pct(20));
    lv_obj_set_height(ui_rollerPasadaTiempoSeg, lv_pct(65));
    lv_obj_set_x(ui_rollerPasadaTiempoSeg, lv_pct(15));
    lv_obj_set_y(ui_rollerPasadaTiempoSeg, lv_pct(4));
    lv_obj_set_align(ui_rollerPasadaTiempoSeg, LV_ALIGN_CENTER);
    lv_obj_set_style_text_letter_space(ui_rollerPasadaTiempoSeg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerPasadaTiempoSeg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerPasadaTiempoSeg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerPasadaTiempoSeg, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerPasadaTiempoSeg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerPasadaTiempoSeg, lv_color_hex(0xACA3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerPasadaTiempoSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerPasadaTiempoSeg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerPasadaTiempoSeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerPasadaTiempoSeg, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerPasadaTiempoSeg, lv_color_hex(0x000597), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerPasadaTiempoSeg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerPasadaTiempoSeg, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerPasadaTiempoSeg, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerPasadaTiempoSeg, lv_color_hex(0x028CC4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerPasadaTiempoSeg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rollerPasadaTiempoSeg, lv_color_hex(0x008DC5), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rollerPasadaTiempoSeg, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerPasadaTiempoSeg, 5, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_rollerPasadaTiempoSeg, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_lblUnitTittlePasadaMin = lv_label_create(ui_groupTipoPasadaTiempo);
    lv_obj_set_width(ui_lblUnitTittlePasadaMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUnitTittlePasadaMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUnitTittlePasadaMin, lv_pct(-15));
    lv_obj_set_y(ui_lblUnitTittlePasadaMin, lv_pct(-46));
    lv_obj_set_align(ui_lblUnitTittlePasadaMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUnitTittlePasadaMin, "(min)");
    lv_obj_set_style_text_color(ui_lblUnitTittlePasadaMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblUnitTittlePasadaMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblUnitTittlePasadaMin, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerPasadaTiempoMin = lv_roller_create(ui_groupTipoPasadaTiempo);
    lv_roller_set_options(ui_rollerPasadaTiempoMin, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollerPasadaTiempoMin, lv_pct(20));
    lv_obj_set_height(ui_rollerPasadaTiempoMin, lv_pct(65));
    lv_obj_set_x(ui_rollerPasadaTiempoMin, lv_pct(-15));
    lv_obj_set_y(ui_rollerPasadaTiempoMin, lv_pct(3));
    lv_obj_set_align(ui_rollerPasadaTiempoMin, LV_ALIGN_CENTER);
    lv_obj_set_style_text_letter_space(ui_rollerPasadaTiempoMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerPasadaTiempoMin, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerPasadaTiempoMin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerPasadaTiempoMin, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerPasadaTiempoMin, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerPasadaTiempoMin, lv_color_hex(0xACA3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerPasadaTiempoMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerPasadaTiempoMin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerPasadaTiempoMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerPasadaTiempoMin, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerPasadaTiempoMin, lv_color_hex(0x000597), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerPasadaTiempoMin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_rollerPasadaTiempoMin, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerPasadaTiempoMin, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerPasadaTiempoMin, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerPasadaTiempoMin, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerPasadaTiempoMin, lv_color_hex(0x008DC5), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerPasadaTiempoMin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rollerPasadaTiempoMin, lv_color_hex(0x008DC5), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rollerPasadaTiempoMin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerPasadaTiempoMin, 5, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_rollerPasadaTiempoMin, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_groupTipoPasadaDistancia = lv_obj_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_groupTipoPasadaDistancia, lv_pct(100));
    lv_obj_set_height(ui_groupTipoPasadaDistancia, lv_pct(50));
    lv_obj_set_align(ui_groupTipoPasadaDistancia, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_groupTipoPasadaDistancia, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_groupTipoPasadaDistancia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_groupTipoPasadaDistancia, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_groupTipoPasadaDistancia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_groupTipoPasadaDistancia);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, lv_pct(0));
    lv_obj_set_y(ui_Label5, lv_pct(-2));
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "(mt)");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Medium_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerPasadaDistancia = lv_roller_create(ui_groupTipoPasadaDistancia);
    lv_roller_set_options(ui_rollerPasadaDistancia,
                          "100\n200\n300\n400\n500\n600\n700\n800\n900\n1000\n1200\n1300\n1400\n1500\n1600\n1700\n1800\n1900\n2000",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rollerPasadaDistancia, lv_pct(25));
    lv_obj_set_height(ui_rollerPasadaDistancia, lv_pct(65));
    lv_obj_set_x(ui_rollerPasadaDistancia, lv_pct(0));
    lv_obj_set_y(ui_rollerPasadaDistancia, lv_pct(3));
    lv_obj_set_align(ui_rollerPasadaDistancia, LV_ALIGN_CENTER);
    lv_obj_set_style_text_letter_space(ui_rollerPasadaDistancia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerPasadaDistancia, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerPasadaDistancia, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerPasadaDistancia, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerPasadaDistancia, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerPasadaDistancia, lv_color_hex(0xACA3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerPasadaDistancia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerPasadaDistancia, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerPasadaDistancia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerPasadaDistancia, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerPasadaDistancia, lv_color_hex(0x000494), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerPasadaDistancia, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerPasadaDistancia, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerPasadaDistancia, &ui_font_Big, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerPasadaDistancia, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerPasadaDistancia, lv_color_hex(0x008DC5), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerPasadaDistancia, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rollerPasadaDistancia, lv_color_hex(0x008DC5), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rollerPasadaDistancia, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerPasadaDistancia, 5, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_rollerPasadaDistancia, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_lblTittleTipoPasadaPor = lv_label_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_lblTittleTipoPasadaPor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleTipoPasadaPor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleTipoPasadaPor, lv_pct(0));
    lv_obj_set_y(ui_lblTittleTipoPasadaPor, lv_pct(1));
    lv_obj_set_align(ui_lblTittleTipoPasadaPor, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleTipoPasadaPor, "PASADA POR:");
    lv_obj_set_style_text_color(ui_lblTittleTipoPasadaPor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleTipoPasadaPor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleTipoPasadaPor, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTittleTipoPasada = lv_label_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_lblTittleTipoPasada, LV_SIZE_CONTENT);   /// 67
    lv_obj_set_height(ui_lblTittleTipoPasada, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleTipoPasada, lv_pct(0));
    lv_obj_set_y(ui_lblTittleTipoPasada, lv_pct(13));
    lv_obj_set_align(ui_lblTittleTipoPasada, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleTipoPasada, "TIEMPO");
    lv_obj_set_style_text_color(ui_lblTittleTipoPasada, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleTipoPasada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleTipoPasada, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleTipoPasada, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swTipoPasada = lv_switch_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_swTipoPasada, lv_pct(25));
    lv_obj_set_height(ui_swTipoPasada, lv_pct(15));
    lv_obj_set_x(ui_swTipoPasada, lv_pct(0));
    lv_obj_set_y(ui_swTipoPasada, lv_pct(-12));
    lv_obj_set_align(ui_swTipoPasada, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swTipoPasada, lv_color_hex(0xD2AB07), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swTipoPasada, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_swTipoPasada, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swTipoPasada, lv_color_hex(0x0C0B00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swTipoPasada, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_swTipoPasada, lv_color_hex(0xFFD800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_swTipoPasada, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_swTipoPasada, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_swTipoPasada, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swTipoPasada, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_swTipoPasada, 125, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swTipoPasada, lv_color_hex(0x028139), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swTipoPasada, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_swTipoPasada, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_swTipoPasada, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_swTipoPasada, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_swTipoPasada, -3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_btnRightSeries = lv_btn_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_btnRightSeries, lv_pct(15));
    lv_obj_set_height(ui_btnRightSeries, lv_pct(100));
    lv_obj_set_align(ui_btnRightSeries, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_btnRightSeries, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRightSeries, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnRightSeries, &ui_img_icn_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRightSeries, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnRightSeries, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRightSeries, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnRightSeries, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_btnRightSeries, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnRightSeries, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_btnLeftToPasadas = lv_btn_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_btnLeftToPasadas, lv_pct(15));
    lv_obj_set_height(ui_btnLeftToPasadas, lv_pct(100));
    lv_obj_set_align(ui_btnLeftToPasadas, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_btnLeftToPasadas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnLeftToPasadas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnLeftToPasadas, &ui_img_icn_arrow_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnLeftToPasadas, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnLeftToPasadas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnLeftToPasadas, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_lblTittleSeries7 = lv_label_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_lblTittleSeries7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries7, lv_pct(-43));
    lv_obj_set_y(ui_lblTittleSeries7, lv_pct(73));
    lv_obj_set_align(ui_lblTittleSeries7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries7, "Config.\nPASADAS");
    lv_obj_set_style_text_color(ui_lblTittleSeries7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleSeries7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries7, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTittleSeries8 = lv_label_create(ui_groupTipoPasadas);
    lv_obj_set_width(ui_lblTittleSeries8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTittleSeries8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTittleSeries8, lv_pct(43));
    lv_obj_set_y(ui_lblTittleSeries8, lv_pct(73));
    lv_obj_set_align(ui_lblTittleSeries8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTittleSeries8, "Config.\nSERIES");
    lv_obj_set_style_text_color(ui_lblTittleSeries8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTittleSeries8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTittleSeries8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTittleSeries8, &ui_font_Small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Buttons3 = lv_obj_create(ui_PROGRAMADO_3);
    lv_obj_set_width(ui_Group_Buttons3, lv_pct(100));
    lv_obj_set_height(ui_Group_Buttons3, lv_pct(15));
    lv_obj_set_x(ui_Group_Buttons3, lv_pct(2));
    lv_obj_set_y(ui_Group_Buttons3, lv_pct(2));
    lv_obj_set_align(ui_Group_Buttons3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Group_Buttons3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Group_Buttons3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Group_Buttons3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Buttons3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Buttons3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroupOk3 = lv_obj_create(ui_Group_Buttons3);
    lv_obj_set_width(ui_GroupOk3, lv_pct(50));
    lv_obj_set_height(ui_GroupOk3, lv_pct(90));
    lv_obj_set_align(ui_GroupOk3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GroupOk3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GroupOk3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GroupOk3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GroupOk3, lv_color_hex(0x00FF1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_GroupOk3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_btnOk3 = lv_btn_create(ui_GroupOk3);
    lv_obj_set_width(ui_btnOk3, lv_pct(100));
    lv_obj_set_height(ui_btnOk3, lv_pct(100));
    lv_obj_set_align(ui_btnOk3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_btnOk3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk3, lv_color_hex(0x001800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnOk3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnOk3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnOk3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnOk3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnOk3, lv_color_hex(0x00FF1A), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnOk3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_imgOk3 = lv_img_create(ui_GroupOk3);
    lv_img_set_src(ui_imgOk3, &ui_img_icn_ok_png);
    lv_obj_set_width(ui_imgOk3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgOk3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgOk3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgOk3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgOk3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imgOk3, 600);
    lv_obj_set_style_img_recolor(ui_imgOk3, lv_color_hex(0x00FF21), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgOk3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_swTipoPasada, ui_event_swTipoPasada, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRightSeries, ui_event_btnRightSeries, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnLeftToPasadas, ui_event_btnLeftToPasadas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnOk3, ui_event_btnOk3, LV_EVENT_ALL, NULL);

}
